version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-Xmx1g -Xms512m"

volumes:
  jenkins_home: