name: Deploy Spring Boot to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/opt/zerde"

      - name: Build and restart Docker container on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Navigating to project directory..."
            cd /opt/zerde

            echo "Granting execute permissions to gradlew..."
            chmod +x ./gradlew

            echo "Cleaning and building Spring Boot application with Gradle..."
            # IMPORTANT: Ensure JDK 21 is installed on your VPS for this step to succeed.
            # Example for Ubuntu/Debian: sudo apt update && sudo apt install openjdk-21-jdk
            ./gradlew clean build

            # Check if the JAR file was successfully created
            if [ -f build/libs/zerde-0.0.1-SNAPSHOT.jar ]; then
              echo "JAR file 'zerde-0.0.1-SNAPSHOT.jar' found. Proceeding with Docker build."
            else
              echo "ERROR: JAR file 'zerde-0.0.1-SNAPSHOT.jar' NOT found after Gradle build."
              echo "Please check the Gradle build output above for errors and ensure JDK 21 is installed on your VPS."
              exit 1 # Exit with an error to fail the workflow
            fi

            echo "Stopping existing Docker containers..."
            docker compose down

            echo "Building Docker image..."
            # The 'version' attribute in docker-compose.yml is obsolete and can be removed.
            docker compose build

            echo "Starting Docker containers..."
            docker compose up -d

            echo "Deployment complete!"