name: Deploy Spring Boot to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/opt/zerde"

      - name: Build and restart Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/zerde
            ./gradlew build -p backend
            docker compose down
            docker compose build
            docker compose up -d
