name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew clean build

      - name: Rename jar for Docker
        run: mv build/libs/*.jar app.jar

      - name: Copy jar and docker files to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          source: |
            app.jar
            Dockerfile
            docker-compose.yml
          target: /opt/zerde

      - name: SSH and deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/zerde
            docker compose down
            docker compose build
            docker compose up -d
